### ISSUE TITLE
Load standard PD_CIF calibration

### ISSUE THREAD

**Issue by jl-wynen** [EasyScience/EasyDiffractionLib#158]
Currently, EasyDiffraction reads calibration / instrument parameters from a custom table: https://github.com/EasyScience/EasyDiffractionLib/blob/bfa5b0aefcc4e8a0a965be166425d21d1c939fff/easydiffraction/Profiles/Experiment.py#L166-L169. However, powder CIF specifies `PD_CALIB_D_TO_TOF`: https://github.com/COMCIFS/Powder_Dictionary/blob/970c2b2850a923796db5f4e9b7207d10ab5fd8e5/cif_pow.dic#L2113. ScippNeutron uses this table and produces files that look like this:
```
loop_
_pd_calib_d_to_tof.id
_pd_calib_d_to_tof.power
_pd_calib_d_to_tof.coeff
DIFB -1 1.2
ZERO 0 3.4
DIFC 1 5.6
DIFA 2 7.8
```

EasyDiffraction should be able to load this data instead of the current `dtt*` fields.

Note: In a meeting we agreed that we should rely on the power instead of the names.

**Comment by AndrewSazonov** [comment]
* Resolved in easydiffraction 0.2.0
* easydiffraction_test.py::test_read_write_tof_cif PASSED https://git.esss.dk/dmsc-nightly/dmsc-nightly/-/jobs/48740
