### ISSUE TITLE
PyPi publish stage fails when direct dependency present

### ISSUE THREAD

**Issue by rozyczko** [EasyScience/EasyDiffractionLib#35]
https://github.com/easyScience/easyDiffractionLib/runs/5077331112?check_suite_focus=true

publishing on PyPi fails with

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: 'cryspy @ git+https://github.com/ikibalin/cryspy.git@bravis_type_fix'
```

The only "solution" proposed in a relevant SO post
https://stackoverflow.com/questions/54887301/how-can-i-use-git-repos-as-dependencies-for-my-pypi-package

is `"Don't use PyPi" is the only solution until they change this.` which is encouraging.

The right solution would be for Iurii to merge the branch into master and publish the package so we can directly refer to it.

**Comment by AndrewSazonov** [comment]
The latest version of Cryspy is published on PyPI
