### ISSUE TITLE
Check and Refactor the development work in `exp` branch of easyDiffractionLib

### ISSUE THREAD

**Issue by wardsimon** [EasyScience/EasyDiffractionLib#4]
The `exp` branch of easyDiffractionLib contains the first work of implementing different experiment types in easyDiffraction. The current work is pre-alpha and need to be looked at before polarized experiments can be implemented

- needs proper review and discussion on how this should be implemented

**Comment by rozyczko** [comment]
TOF is already based on this, isn't it?
